---

 - name: Running Password change Workflow
   hosts: all
   gather_facts: False
   # Skip facts gathering. Causes timeout errors with proxy .re hosts

   vars:
     tmp_file: '/home/ansible/.password.txt'
   
   pre_tasks:

     - name: Running pre-flight checks prior to workflow
       block:
         
         - name: Checking if vault file exists if password has not been provided
           ansible.builtin.stat:
             path: vars/secrets.yml
           register: pwf
           when: password is not defined
           tags:
             - always

         - ansible.builtin.fail:
             msg: "A password has not been provided by user or file. Or file checksum is invalid."
           when: 
             - ( not pwf.stat.exists ) or ( pwf.stat.checksum != current_secrets_checksum ) 
             - password is not defined
           tags:
             - always

       delegate_to: localhost

   tasks:

     - name: Use vaulted file if provided
       include_vars:
         file: vars/secrets.yml
         name: password
       when: not password is defined
       tags:
         - root_pass
         - ad-hoc

     - name: Change the root password provided by user.
       become: true
       become_user: root 
       ansible.builtin.user:
         name: root 
         state: present
         password: "{{ password | password_hash('sha512') }}"
       when: password is string
       tags:
         - root_pass
         - ad-hoc

     - name: Change the root password provided by secrets file
       become: true
       become_user: root
       ansible.builtin.user:
         name: root
         state: present
         password: "{{ password['password'] | password_hash('sha512') }}"
       when: password is mapping
       tags:
         - root_pass    
         - ad-hoc

     - name: Running SSH key exchange workflow for hosts with defined exchange
       block:

         - name: Lock Puppet agent 
           ansible.builtin.command: /opt/puppetlabs/bin/puppet agent --disable
        
         - name: Enable root login for key exchange
           ansible.builtin.lineinfile:
             path: /etc/ssh/sshd_config
             regexp: '^PermitRootLogin '
             insertafter: '^#PermitRootLogin '
             line: PermitRootLogin yes

         - name: Restart SSH 
           ansible.builtin.service:
             name: sshd 
             state: restarted 
           ignore_unreachable: yes

         - name: Reconnect after restarting
           ansible.builtin.wait_for_connection:
             connect_timeout: 15
             sleep: 5 
             timeout: 300

         - name: Create a new SSH key pair  
           community.crypto.openssh_keypair:
             path: ~/.ssh/id_rsa
             type: rsa
             force: yes
           when:
             - clients is defined
             - clients|length > 0 
             
         - name: Copy public key to hosts for password-less ssh 
           ansible.builtin.expect: 
             command: ssh-copy-id "{{ item }}"
             responses: 
               (?i)password: "{{ password }}"
           loop: "{{ clients }}"
           when:
             - clients is defined
             - clients|length > 0

         - name: Unlock Puppet agent
           ansible.builtin.command: /opt/puppetlabs/bin/puppet agent --enable

       tags:
        - ssh-keys


   
